In [157]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [158]:
Airline_Operations=pd.read_csv(r"D:\Final Project\Final Project\Airline_Operations.csv")
Bookings=pd.read_csv(r"D:\Final Project\Final Project\Bookings.csv")
Customers=pd.read_csv(r"D:\Final Project\Final Project\Customers.csv")
Flights=pd.read_csv(r"D:\Final Project\Final Project\Flights.csv")

In [159]:
Airline_Operations.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Operation_ID             10000 non-null  str
 1   Airline_ID               10000 non-null  str
 2   Airline_Name             10000 non-null  str
 3   Aircraft_ID              10000 non-null  str
 4   Aircraft_Type            9823 non-null   str
 5   Fleet_Age_Years          10000 non-null  int64
 6   Crew_Size                10000 non-null  int64
 7   Maintenance_Status       9712 non-null   str
 8   Maintenance_Cost         10000 non-null  float64
 9   Fuel_Consumption_Liters  10000 non-null  int64
 10  Operating_Cost           10000 non-null  float64
 11  Safety_Rating            9780 non-null   float64
 12  Operational_Region       10000 non-null  str
dtypes: float64(3), int64(3), str(7)
memory usage: 1.6 MB

In [160]:
Airline_Operations.head()

,Operation_ID,Airline_ID,Airline_Name,Aircraft_ID,Aircraft_Type,Fleet_Age_Years,Crew_Size,Maintenance_Status,Maintenance_Cost,Fuel_Consumption_Liters,Operating_Cost,Safety_Rating,Operational_Region
0,OP00001,AL07,Singapore Airlines,AC00001,NaN,1,15,Good,25188.72,74816,148336.07,4.0,Europe
1,OP00002,AL04,Lufthansa,AC00002,Airbus A380,1,11,Needs Inspection,26331.53,125157,99835.44,3.0,North America
2,OP00003,AL08,British Airways,AC00003,Boeing 787,25,15,Needs Inspection,42516.13,140383,75896.48,3.0,Asia Pacific
3,OP00004,AL05,Emirates,AC00004,Airbus A350,20,14,Good,34960.25,97878,161809.64,3.0,Middle East
4,OP00005,AL07,Singapore Airlines,AC00005,Airbus A380,17,9,Needs Inspection,24492.05,82383,200948.27,3.0,Europe

In [11]:
Airline_Operations.sample()

,Operation_ID,Airline_ID,Airline_Name,Aircraft_ID,Aircraft_Type,Fleet_Age_Years,Crew_Size,Maintenance_Status,Maintenance_Cost,Fuel_Consumption_Liters,Operating_Cost,Safety_Rating,Operational_Region
5691,OP05692,AL09,Air France,AC05692,Boeing 787,6,10,Fair,49870.35,32468,81117.18,2.0,South America

In [161]:
Airline_Operations.tail()

,Operation_ID,Airline_ID,Airline_Name,Aircraft_ID,Aircraft_Type,Fleet_Age_Years,Crew_Size,Maintenance_Status,Maintenance_Cost,Fuel_Consumption_Liters,Operating_Cost,Safety_Rating,Operational_Region
9995,OP09996,AL07,Singapore Airlines,AC09996,Airbus A380,16,6,Under Maintenance,18366.73,26060,30335.19,3.0,Europe
9996,OP09997,AL10,Cathay Pacific,AC09997,Boeing 737,7,8,Needs Inspection,46533.19,129847,78990.76,3.0,Asia Pacific
9997,OP09998,AL03,American Airlines,AC09998,Airbus A380,15,15,Under Maintenance,32959.74,67002,124503.62,4.0,Europe
9998,OP09999,AL10,Cathay Pacific,AC09999,Airbus A380,23,4,Under Maintenance,22374.82,57815,142702.83,5.0,North America
9999,OP10000,AL05,Emirates,AC10000,Airbus A350,2,9,Good,5488.14,24276,118244.05,4.0,Europe

In [162]:
Airline_Operations.describe()

,Fleet_Age_Years,Crew_Size,Maintenance_Cost,Fuel_Consumption_Liters,Operating_Cost,Safety_Rating
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,9780.000000
mean,12.975000,9.566800,27421.974462,80375.245300,136055.696421,2.999284
std,7.206703,3.434227,13012.267145,40462.816298,66359.194678,1.418077
min,1.000000,4.000000,5004.610000,10005.000000,20010.930000,1.000000
25%,7.000000,7.000000,16275.985000,45232.500000,78777.202500,2.000000
50%,13.000000,10.000000,27313.615000,80299.000000,136075.520000,3.000000
75%,19.000000,13.000000,38757.305000,115032.250000,194211.302500,4.000000
max,25.000000,15.000000,49995.490000,149999.000000,249975.860000,5.000000

In [163]:
Airline_Operations.isnull().sum()

Operation_ID                 0
Airline_ID                   0
Airline_Name                 0
Aircraft_ID                  0
Aircraft_Type              177
Fleet_Age_Years              0
Crew_Size                    0
Maintenance_Status         288
Maintenance_Cost             0
Fuel_Consumption_Liters      0
Operating_Cost               0
Safety_Rating              220
Operational_Region           0
dtype: int64

In [14]:
round((Airline_Operations.isnull().sum() / len(Airline_Operations) * 100), 1)

Operation_ID               0.0
Airline_ID                 0.0
Airline_Name               0.0
Aircraft_ID                0.0
Aircraft_Type              1.8
Fleet_Age_Years            0.0
Crew_Size                  0.0
Maintenance_Status         2.9
Maintenance_Cost           0.0
Fuel_Consumption_Liters    0.0
Operating_Cost             0.0
Safety_Rating              2.2
Operational_Region         0.0
dtype: float64

In [16]:
Airline_Operations.duplicated().sum()

np.int64(0)

In [19]:
Airline_Operations[Airline_Operations.duplicated()]

Empty DataFrame
Columns: [Operation_ID, Airline_ID, Airline_Name, Aircraft_ID, Aircraft_Type, Fleet_Age_Years, Crew_Size, Maintenance_Status, Maintenance_Cost, Fuel_Consumption_Liters, Operating_Cost, Safety_Rating, Operational_Region]
Index: []

In [21]:
Airline_Operations["Airline_Name"].value_counts()

Airline_Name
Delta Airlines        1053
Cathay Pacific        1034
Qatar Airways         1021
Singapore Airlines    1017
American Airlines      996
Air France             994
United Airlines        985
Lufthansa              971
British Airways        967
Emirates               962
Name: count, dtype: int64

In [22]:
Airline_Operations["Aircraft_Type"].value_counts()

Aircraft_Type
Boeing 777     1696
Airbus A350    1667
Airbus A380    1641
Airbus A320    1640
Boeing 737     1595
Boeing 787     1584
Name: count, dtype: int64

In [23]:
Airline_Operations["Maintenance_Status"].value_counts()

Maintenance_Status
Under Maintenance    2485
Fair                 2477
Needs Inspection     2394
Good                 2356
Name: count, dtype: int64

In [25]:
Airline_Operations["Operational_Region"].value_counts()

Operational_Region
North America    2083
South America    2018
Asia Pacific     1987
Europe           1977
Middle East      1935
Name: count, dtype: int64

In [28]:
Airline_Operations.drop_duplicates(inplace=True)

In [29]:
Airline_Operations["Aircraft_Type"].mode()

0    Boeing 777
Name: Aircraft_Type, dtype: str

In [184]:
Airline_Operations["Aircraft_Type"]=Airline_Operations["Aircraft_Type"].fillna(Airline_Operations["Aircraft_Type"].mode()[0])

In [32]:
Airline_Operations["Maintenance_Status"].mode()

0    Under Maintenance
Name: Maintenance_Status, dtype: str

In [164]:
Airline_Operations["Maintenance_Status"]=Airline_Operations["Maintenance_Status"].fillna(Airline_Operations["Maintenance_Status"].mode()[0])

In [165]:
Airline_Operations["Safety_Rating"]=Airline_Operations["Safety_Rating"].fillna(Airline_Operations["Safety_Rating"].median())

In [166]:
Airline_Operations["Safety_Rating"]=Airline_Operations["Safety_Rating"].astype(int)

In [185]:
Airline_Operations.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Operation_ID             10000 non-null  str
 1   Airline_ID               10000 non-null  str
 2   Airline_Name             10000 non-null  str
 3   Aircraft_ID              10000 non-null  str
 4   Aircraft_Type            10000 non-null  str
 5   Fleet_Age_Years          10000 non-null  int64
 6   Crew_Size                10000 non-null  int64
 7   Maintenance_Status       10000 non-null  str
 8   Maintenance_Cost         10000 non-null  float64
 9   Fuel_Consumption_Liters  10000 non-null  int64
 10  Operating_Cost           10000 non-null  float64
 11  Safety_Rating            10000 non-null  int64
 12  Operational_Region       10000 non-null  str
dtypes: float64(2), int64(4), str(7)
memory usage: 1.6 MB

In [43]:
Bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 340000 entries, 0 to 339999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Booking_ID            340000 non-null  str
 1   Customer_ID           340000 non-null  str
 2   Flight_ID             340000 non-null  str
 3   Booking_Date          340000 non-null  str
 4   Travel_Date           340000 non-null  str
 5   Cabin_Class           340000 non-null  str
 6   Ticket_Type           340000 non-null  str
 7   Ticket_Price          340000 non-null  float64
 8   Discount_Percentage   340000 non-null  int64
 9   Discount_Amount       340000 non-null  float64
 10  Final_Price           340000 non-null  float64
 11  Baggage_Allowance_KG  340000 non-null  int64
 12  Extra_Baggage_KG      340000 non-null  int64
 13  Payment_Method        340000 non-null  str
 14  Booking_Channel       340000 non-null  str
 15  Seat_Number           329922 non-null  str
 16  Meal_Preference       322769 non-null  str
 17  Insurance_Added       333208 non-null  str
 18  Cancellation_Status   340000 non-null  str
 19  Satisfaction_Score    323078 non-null  float64
 20  Refund_Amount         340000 non-null  float64
dtypes: float64(5), int64(3), str(13)
memory usage: 86.7 MB

In [52]:
Bookings.head()

,Booking_ID,Customer_ID,Flight_ID,Booking_Date,Travel_Date,Cabin_Class,Ticket_Type,Ticket_Price,Discount_Percentage,Discount_Amount,...,Baggage_Allowance_KG,Extra_Baggage_KG,Payment_Method,Booking_Channel,Seat_Number,Meal_Preference,Insurance_Added,Cancellation_Status,Satisfaction_Score,Refund_Amount
0,BK000001,CU011907,FL45626,2025-04-12,2025-06-11,Economy,Standard,1230.26,20,246.05,...,15,0,Bank Transfer,Airport Counter,1C,Halal,No,Active,3.0,0.0
1,BK000002,CU090222,FL33447,2022-03-31,2022-06-12,Economy,Standard,205.09,0,0.00,...,15,0,Credit Card,Airport Counter,26C,Vegan,No,Active,2.0,0.0
2,BK000003,CU038224,FL29546,2024-07-09,2024-08-22,Business,Flexible,1948.17,0,0.00,...,30,0,Bank Transfer,Airport Counter,56F,Vegetarian,Yes,Active,2.0,0.0
3,BK000004,CU019018,FL44444,2023-11-14,2024-03-27,Economy,Non-Refundable,333.65,5,16.68,...,40,5,Credit Card,Travel Agent,11B,Kosher,Yes,Active,3.0,0.0
4,BK000005,CU066173,FL19688,2023-04-06,2023-08-19,Economy,Standard,932.70,0,0.00,...,0,0,PayPal,Mobile App,50F,Vegan,No,Active,3.0,0.0

In [45]:
Bookings.describe()

,Ticket_Price,Discount_Percentage,Discount_Amount,Final_Price,Baggage_Allowance_KG,Extra_Baggage_KG,Satisfaction_Score,Refund_Amount
count,340000.000000,340000.000000,340000.000000,340000.000000,340000.000000,340000.000000,323078.000000,340000.000000
mean,1050.750267,3.989794,41.884387,1008.865880,21.638374,1.992176,2.995673,81.063137
std,548.940805,5.815916,72.425220,531.536799,13.576810,4.835452,1.413890,277.694172
min,100.000000,0.000000,0.000000,80.030000,0.000000,0.000000,1.000000,0.000000
25%,574.987500,0.000000,0.000000,549.967500,15.000000,0.000000,2.000000,0.000000
50%,1051.815000,0.000000,0.000000,1005.410000,23.000000,0.000000,3.000000,0.000000
75%,1526.850000,10.000000,63.620000,1460.110000,30.000000,0.000000,4.000000,0.000000
max,2000.000000,20.000000,399.960000,2000.000000,40.000000,20.000000,5.000000,1600.000000

In [46]:
Bookings.isnull().sum()

Booking_ID                  0
Customer_ID                 0
Flight_ID                   0
Booking_Date                0
Travel_Date                 0
Cabin_Class                 0
Ticket_Type                 0
Ticket_Price                0
Discount_Percentage         0
Discount_Amount             0
Final_Price                 0
Baggage_Allowance_KG        0
Extra_Baggage_KG            0
Payment_Method              0
Booking_Channel             0
Seat_Number             10078
Meal_Preference         17231
Insurance_Added          6792
Cancellation_Status         0
Satisfaction_Score      16922
Refund_Amount               0
dtype: int64

In [47]:
round((Bookings.isnull().sum() / len(Bookings) * 100), 1)

Booking_ID              0.0
Customer_ID             0.0
Flight_ID               0.0
Booking_Date            0.0
Travel_Date             0.0
Cabin_Class             0.0
Ticket_Type             0.0
Ticket_Price            0.0
Discount_Percentage     0.0
Discount_Amount         0.0
Final_Price             0.0
Baggage_Allowance_KG    0.0
Extra_Baggage_KG        0.0
Payment_Method          0.0
Booking_Channel         0.0
Seat_Number             3.0
Meal_Preference         5.1
Insurance_Added         2.0
Cancellation_Status     0.0
Satisfaction_Score      5.0
Refund_Amount           0.0
dtype: float64

In [49]:
Bookings.duplicated().sum()

np.int64(0)

In [50]:
Bookings[Bookings.duplicated()]

Empty DataFrame
Columns: [Booking_ID, Customer_ID, Flight_ID, Booking_Date, Travel_Date, Cabin_Class, Ticket_Type, Ticket_Price, Discount_Percentage, Discount_Amount, Final_Price, Baggage_Allowance_KG, Extra_Baggage_KG, Payment_Method, Booking_Channel, Seat_Number, Meal_Preference, Insurance_Added, Cancellation_Status, Satisfaction_Score, Refund_Amount]
Index: []

[0 rows x 21 columns]

In [187]:
Bookings.drop_duplicates(inplace=True)

In [188]:
Bookings["Booking_Date"]=pd.to_datetime(Bookings["Booking_Date"])

In [189]:
Bookings["Travel_Date"]=pd.to_datetime(Bookings["Travel_Date"])

In [193]:
Bookings["Satisfaction_Score"]=Bookings["Satisfaction_Score"].astype(int)

In [194]:
Bookings["Seat_Number"].mode()

0    38C
Name: Seat_Number, dtype: str

In [63]:
Bookings["Meal_Preference"].mode()

0    Kosher
Name: Meal_Preference, dtype: str

In [64]:
Bookings["Insurance_Added"].mode()

0    No
Name: Insurance_Added, dtype: str

In [195]:
Bookings["Seat_Number"]=Bookings["Seat_Number"].fillna(Bookings["Seat_Number"].mode()[0])

In [197]:
Bookings["Meal_Preference"]=Bookings["Meal_Preference"].fillna(Bookings["Meal_Preference"].mode()[0])

In [196]:
Bookings["Insurance_Added"]=Bookings["Insurance_Added"].fillna(Bookings["Insurance_Added"].mode()[0])

In [191]:
Bookings["Satisfaction_Score"]=Bookings["Satisfaction_Score"].fillna(Bookings["Satisfaction_Score"].median())

In [198]:
Bookings["Payment_Method"].value_counts()

Payment_Method
Bank Transfer    85072
PayPal           85046
Debit Card       84964
Credit Card      84918
Name: count, dtype: int64

In [199]:
Bookings.info()

<class 'pandas.DataFrame'>
RangeIndex: 340000 entries, 0 to 339999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Booking_ID            340000 non-null  str
 1   Customer_ID           340000 non-null  str
 2   Flight_ID             340000 non-null  str
 3   Booking_Date          340000 non-null  datetime64[us]
 4   Travel_Date           340000 non-null  datetime64[us]
 5   Cabin_Class           340000 non-null  str
 6   Ticket_Type           340000 non-null  str
 7   Ticket_Price          340000 non-null  float64
 8   Discount_Percentage   340000 non-null  int64
 9   Discount_Amount       340000 non-null  float64
 10  Final_Price           340000 non-null  float64
 11  Baggage_Allowance_KG  340000 non-null  int64
 12  Extra_Baggage_KG      340000 non-null  int64
 13  Payment_Method        340000 non-null  str
 14  Booking_Channel       340000 non-null  str
 15  Seat_Number           340000 non-null  str
 16  Meal_Preference       340000 non-null  str
 17  Insurance_Added       340000 non-null  str
 18  Cancellation_Status   340000 non-null  str
 19  Satisfaction_Score    340000 non-null  int64
 20  Refund_Amount         340000 non-null  float64
dtypes: datetime64[us](2), float64(4), int64(4), str(11)
memory usage: 80.2 MB

In [200]:
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Customer_ID               100000 non-null  str
 1   First_Name                100000 non-null  str
 2   Last_Name                 100000 non-null  str
 3   Gender                    100000 non-null  str
 4   Date_of_Birth             100000 non-null  str
 5   Country                   100000 non-null  str
 6   City                      100000 non-null  str
 7   Passport_Country          96983 non-null   str
 8   Loyalty_Program           100000 non-null  str
 9   Loyalty_Tier              40150 non-null   str
 10  Membership_Date           40150 non-null   str
 11  Preferred_Cabin           96895 non-null   str
 12  Preferred_Payment_Method  100000 non-null  str
 13  Customer_Satisfaction     95016 non-null   float64
 14  Annual_Travel_Frequency   100000 non-null  int64
dtypes: float64(1), int64(1), str(13)
memory usage: 18.3 MB

In [85]:
Customers.head()

,Customer_ID,First_Name,Last_Name,Gender,Date_of_Birth,Country,City,Passport_Country,Loyalty_Program,Loyalty_Tier,Membership_Date,Preferred_Cabin,Preferred_Payment_Method,Customer_Satisfaction,Annual_Travel_Frequency
0,CU000001,John,Chen,F,1963-07-07,UK,City_17,USA,Yes,Gold,2021-08-05,Business,Crypto,5.0,9
1,CU000002,Ava,Jones,M,1992-07-11,Canada,City_15,NaN,Yes,Gold,2021-03-25,Economy,Credit Card,2.0,5
2,CU000003,Emma,Rodriguez,F,1998-05-29,Germany,City_28,Australia,Yes,Platinum,2018-05-08,Economy,PayPal,5.0,19
3,CU000004,Isabella,Martinez,F,1995-03-20,Singapore,City_4,France,No,NaN,NaN,First,Debit Card,1.0,11
4,CU000005,Sophia,Brown,M,1983-11-23,Canada,City_40,USA,No,NaN,NaN,First,Credit Card,2.0,15

In [110]:
Customers.sample(10)

,Customer_ID,First_Name,Last_Name,Gender,Date_of_Birth,Country,City,Passport_Country,Loyalty_Program,Loyalty_Tier,Membership_Date,Preferred_Cabin,Preferred_Payment_Method,Customer_Satisfaction,Annual_Travel_Frequency
91343,CU091344,Sophia,Brown,F,1972-10-28,Canada,City_21,Japan,No,Gold,2020-09-09,Economy,Debit Card,5,15
82665,CU082666,Liam,Williams,M,1989-10-02,USA,City_39,UK,Yes,Gold,2015-01-17,Business,Credit Card,2,9
23275,CU023276,Ahmed,Davis,M,1961-07-14,Brazil,City_2,Canada,No,Gold,2020-09-09,Business,Crypto,1,18
64030,CU064031,Ali,Ali,F,1978-10-13,Singapore,City_40,Singapore,Yes,Gold,2016-07-16,Economy,PayPal,5,9
31506,CU031507,Maria,Chen,Other,1986-07-16,UK,City_5,Australia,Yes,Gold,2022-06-26,Economy,PayPal,5,14
60965,CU060966,John,Martinez,F,1956-09-16,Japan,City_35,Australia,No,Gold,2020-09-09,Economy,Debit Card,1,3
7151,CU007152,Liam,Smith,F,1953-10-13,Japan,City_36,France,Yes,Gold,2018-06-08,Economy,Credit Card,2,12
49452,CU049453,Maria,Ali,F,1952-08-05,Brazil,City_35,Singapore,No,Gold,2020-09-09,Economy,Debit Card,4,16
18206,CU018207,Olivia,Miller,M,1974-06-21,Germany,City_49,Singapore,No,Gold,2020-09-09,Economy,Debit Card,3,6
29791,CU029792,James,Rodriguez,Other,1972-06-30,Germany,City_22,Singapore,No,Gold,2020-09-09,Economy,Crypto,1,2

In [87]:
Customers.tail()

,Customer_ID,First_Name,Last_Name,Gender,Date_of_Birth,Country,City,Passport_Country,Loyalty_Program,Loyalty_Tier,Membership_Date,Preferred_Cabin,Preferred_Payment_Method,Customer_Satisfaction,Annual_Travel_Frequency
99995,CU099996,Noah,Miller,M,1956-11-18,USA,City_24,USA,Yes,Gold,2021-03-13,Economy,Debit Card,3.0,14
99996,CU099997,Emma,Williams,M,1986-02-08,Canada,City_25,France,No,NaN,NaN,Economy,Credit Card,5.0,13
99997,CU099998,Ali,Rodriguez,F,1982-11-16,Japan,City_32,Singapore,Yes,Gold,2019-06-20,Economy,Debit Card,3.0,16
99998,CU099999,Ava,Garcia,F,1967-07-25,UAE,City_40,Japan,Yes,Gold,2015-11-19,First,Debit Card,4.0,12
99999,CU100000,Liam,Jones,F,1980-09-07,Brazil,City_37,Singapore,Yes,Silver,2022-09-17,First,Debit Card,3.0,1

In [84]:
Customers.describe()

       Customer_Satisfaction  Annual_Travel_Frequency
count           95016.000000            100000.000000
mean                3.004347                 9.983750
std                 1.414017                 5.468536
min                 1.000000                 1.000000
25%                 2.000000                 5.000000
50%                 3.000000                10.000000
75%                 4.000000                15.000000
max                 5.000000                19.000000

In [95]:
Customers.isnull().sum()

Customer_ID                     0
First_Name                      0
Last_Name                       0
Gender                          0
Date_of_Birth                   0
Country                         0
City                            0
Passport_Country             3017
Loyalty_Program                 0
Loyalty_Tier                59850
Membership_Date             59850
Preferred_Cabin              3105
Preferred_Payment_Method        0
Customer_Satisfaction        4984
Annual_Travel_Frequency         0
dtype: int64

In [89]:
Customers.duplicated().sum()

np.int64(0)

In [201]:
Customers.drop_duplicates(inplace=True)

In [202]:
Customers["Date_of_Birth"]=pd.to_datetime(Customers["Date_of_Birth"])

In [203]:
Customers["Date_of_Birth"]=pd.to_datetime(Customers["Date_of_Birth"])

In [204]:
Customers["Membership_Date"]=pd.to_datetime(Customers["Membership_Date"])

In [205]:
Customers["Passport_Country"].mode()

0    Singapore
Name: Passport_Country, dtype: str

In [97]:
Customers["Loyalty_Tier"].mode()

0    Gold
Name: Loyalty_Tier, dtype: str

In [98]:
Customers["Membership_Date"].mode()

0   2020-09-09
Name: Membership_Date, dtype: datetime64[us]

In [100]:
Customers["Preferred_Cabin"].mode()

0    Economy
Name: Preferred_Cabin, dtype: str

In [99]:
Customers["Customer_Satisfaction"].mode()

0    5.0
Name: Customer_Satisfaction, dtype: float64

In [206]:
Customers["Passport_Country"]=Customers["Passport_Country"].fillna(Customers["Passport_Country"].mode()[0])

In [207]:
Customers["Loyalty_Tier"]=Customers["Loyalty_Tier"].fillna(Customers["Loyalty_Tier"].mode()[0])

In [208]:
Customers["Membership_Date"]=Customers["Membership_Date"].fillna(Customers["Membership_Date"].mode()[0])

In [209]:
Customers["Preferred_Cabin"]=Customers["Preferred_Cabin"].fillna(Customers["Preferred_Cabin"].mode()[0])

In [210]:
Customers["Customer_Satisfaction"]=Customers["Customer_Satisfaction"].fillna(Customers["Customer_Satisfaction"].mode()[0])

In [211]:
Customers["Customer_Satisfaction"]=Customers["Customer_Satisfaction"].astype(int)

In [111]:
Customers["Country"].value_counts()

Country
Australia    10141
Brazil       10112
Canada       10041
Japan        10020
UAE          10016
Germany       9968
Singapore     9932
UK            9931
France        9927
USA           9912
Name: count, dtype: int64

In [212]:
Customers["Country"]=Customers["Country"].replace({"UAE":"United Arab Emirates","UK":"United Kingdom","USA":"United States America"})

In [116]:
Customers["Passport_Country"].value_counts()

Passport_Country
Singapore    12835
Germany       9782
Canada        9753
Brazil        9745
UK            9724
UAE           9687
Australia     9672
France        9640
USA           9594
Japan         9568
Name: count, dtype: int64

In [213]:
Customers["Passport_Country"]=Customers["Passport_Country"].replace({"UAE":"United Arab Emirates","UK":"United Kingdom","USA":"United States America"})

In [214]:
Customers["Preferred_Payment_Method"].value_counts()

Preferred_Payment_Method
Crypto         25139
Debit Card     25062
PayPal         24964
Credit Card    24835
Name: count, dtype: int64

In [215]:
Customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Customer_ID               100000 non-null  str
 1   First_Name                100000 non-null  str
 2   Last_Name                 100000 non-null  str
 3   Gender                    100000 non-null  str
 4   Date_of_Birth             100000 non-null  datetime64[us]
 5   Country                   100000 non-null  str
 6   City                      100000 non-null  str
 7   Passport_Country          100000 non-null  str
 8   Loyalty_Program           100000 non-null  str
 9   Loyalty_Tier              100000 non-null  str
 10  Membership_Date           100000 non-null  datetime64[us]
 11  Preferred_Cabin           100000 non-null  str
 12  Preferred_Payment_Method  100000 non-null  str
 13  Customer_Satisfaction     100000 non-null  int64
 14  Annual_Travel_Frequency   100000 non-null  int64
dtypes: datetime64[us](2), int64(2), str(11)
memory usage: 18.1 MB

In [123]:
Flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                50000 non-null  str
 1   Operation_ID             50000 non-null  str
 2   Flight_Number            50000 non-null  str
 3   Origin_Airport           50000 non-null  str
 4   Destination_Airport      50000 non-null  str
 5   Departure_Date           50000 non-null  str
 6   Scheduled_Departure      50000 non-null  str
 7   Actual_Departure         48980 non-null  str
 8   Scheduled_Arrival        50000 non-null  str
 9   Actual_Arrival           50000 non-null  str
 10  Flight_Duration_Minutes  50000 non-null  int64
 11  Distance_KM              50000 non-null  int64
 12  Flight_Status            50000 non-null  str
 13  Gate_Number              48975 non-null  str
 14  Runway_Number            50000 non-null  str
 15  Delay_Minutes            48550 non-null  float64
 16  Cancellation_Reason      4757 non-null   str
dtypes: float64(1), int64(2), str(14)
memory usage: 12.5 MB

In [124]:
Flights.head()

,Flight_ID,Operation_ID,Flight_Number,Origin_Airport,Destination_Airport,Departure_Date,Scheduled_Departure,Actual_Departure,Scheduled_Arrival,Actual_Arrival,Flight_Duration_Minutes,Distance_KM,Flight_Status,Gate_Number,Runway_Number,Delay_Minutes,Cancellation_Reason
0,FL00001,OP01633,FN6830,LAX,SIN,2024-07-06,2024-07-06 00:00:00,2024-07-06 00:04:00,2024-07-06 13:00:00,2024-07-06 10:58:00,699,11257,Delayed,G27,35R,246.0,NaN
1,FL00002,OP04043,FN359,ATL,DFW,2026-12-05,2026-12-05 00:00:00,2026-12-05 00:29:00,2026-12-05 04:00:00,2026-12-05 08:43:00,793,2863,Delayed,G36,22C,62.0,NaN
2,FL00003,OP03924,FN4119,JFK,YYZ,2025-12-07,2025-12-07 00:00:00,2025-12-07 00:13:00,2025-12-07 13:00:00,2025-12-07 08:04:00,170,4788,Cancelled,G26,14R,0.0,Weather
3,FL00004,OP03170,FN3798,DFW,ORD,2023-08-12,2023-08-12 00:00:00,2023-08-12 01:17:00,2023-08-12 08:00:00,2023-08-12 09:26:00,205,4309,Cancelled,G36,10R,0.0,Crew Shortage
4,FL00005,OP08900,FN1580,HND,JFK,2022-09-21,2022-09-21 00:00:00,2022-09-20 23:21:00,2022-09-21 04:00:00,2022-09-21 12:29:00,117,2329,Delayed,G98,28R,27.0,NaN

In [137]:
Flights.sample(5)

,Flight_ID,Operation_ID,Flight_Number,Origin_Airport,Destination_Airport,Departure_Date,Scheduled_Departure,Actual_Departure,Scheduled_Arrival,Actual_Arrival,Flight_Duration_Minutes,Distance_KM,Flight_Status,Gate_Number,Runway_Number,Delay_Minutes,Cancellation_Reason
17290,FL17291,OP08280,FN5450,CDG,DFW,2024-10-18,2024-10-18,2024-10-18 00:37:00,2024-10-18 06:00:00,2024-10-18 06:32:00,616,8015,On Time,G43,28L,0.0,NaN
37899,FL37900,OP06391,FN2940,DFW,FRA,2023-04-08,2023-04-08,2023-04-08 00:12:00,2023-04-08 13:00:00,2023-04-08 07:42:00,662,9814,On Time,G96,16C,0.0,NaN
28554,FL28555,OP07152,FN6465,LAX,SYD,2023-01-21,2023-01-21,2023-01-21 00:37:00,2023-01-21 02:00:00,2023-01-21 07:16:00,189,8545,Delayed,G30,12C,28.0,NaN
7649,FL07650,OP08414,FN7879,CDG,SYD,2022-03-22,2022-03-22,2022-03-22 00:53:00,2022-03-22 12:00:00,2022-03-22 06:34:00,874,1781,On Time,G55,16C,0.0,NaN
47582,FL47583,OP02938,FN6200,YYZ,AMS,2025-10-29,2025-10-29,2025-10-29 00:10:00,2025-10-29 10:00:00,2025-10-29 05:58:00,104,8923,Cancelled,G96,29L,0.0,Crew Shortage

In [125]:
Flights.tail()

,Flight_ID,Operation_ID,Flight_Number,Origin_Airport,Destination_Airport,Departure_Date,Scheduled_Departure,Actual_Departure,Scheduled_Arrival,Actual_Arrival,Flight_Duration_Minutes,Distance_KM,Flight_Status,Gate_Number,Runway_Number,Delay_Minutes,Cancellation_Reason
49995,FL49996,OP03219,FN9137,LAX,HND,2023-10-24,2023-10-24 00:00:00,2023-10-24 00:21:00,2023-10-24 13:00:00,2023-10-24 07:02:00,369,9570,Cancelled,G52,15C,0.0,Air Traffic Control
49996,FL49997,OP00924,FN2115,CDG,LAX,2023-03-25,2023-03-25 00:00:00,2023-03-25 01:08:00,2023-03-25 06:00:00,2023-03-25 11:15:00,388,10879,On Time,G33,5C,0.0,NaN
49997,FL49998,OP07454,FN5239,AMS,ATL,2026-02-03,2026-02-03 00:00:00,2026-02-02 23:36:00,2026-02-03 02:00:00,2026-02-03 11:30:00,114,10545,On Time,G90,19R,0.0,NaN
49998,FL49999,OP00923,FN6440,JFK,DXB,2026-05-05,2026-05-05 00:00:00,2026-05-05 00:20:00,2026-05-05 07:00:00,2026-05-05 02:13:00,496,9801,On Time,G6,14C,0.0,NaN
49999,FL50000,OP08613,FN5021,YYZ,HND,2022-08-20,2022-08-20 00:00:00,2022-08-20 00:41:00,2022-08-20 05:00:00,2022-08-20 07:49:00,895,7458,On Time,G48,24R,0.0,NaN

In [127]:
Flights.describe()

       Flight_Duration_Minutes   Distance_KM  Delay_Minutes
count             50000.000000  50000.000000   48550.000000
mean                477.980000   6247.951520      31.133821
std                 242.456006   3320.446191      72.458426
min                  60.000000    500.000000       0.000000
25%                 268.000000   3356.750000       0.000000
50%                 477.000000   6236.000000       0.000000
75%                 688.000000   9134.000000       0.000000
max                 899.000000  11999.000000     299.000000

In [128]:
Flights.isnull().sum()

Flight_ID                      0
Operation_ID                   0
Flight_Number                  0
Origin_Airport                 0
Destination_Airport            0
Departure_Date                 0
Scheduled_Departure            0
Actual_Departure            1020
Scheduled_Arrival              0
Actual_Arrival                 0
Flight_Duration_Minutes        0
Distance_KM                    0
Flight_Status                  0
Gate_Number                 1025
Runway_Number                  0
Delay_Minutes               1450
Cancellation_Reason        45243
dtype: int64

In [131]:
Flights.duplicated().sum()

np.int64(0)

In [216]:
Flights.drop_duplicates(inplace=True)

In [217]:
Flights["Departure_Date"]=pd.to_datetime(Flights["Departure_Date"])

In [218]:
Flights["Scheduled_Departure"]=pd.to_datetime(Flights["Scheduled_Departure"])

In [ ]:
Flights["Actual_Departure"]=pd.to_datetime(Flights["Departure_Date"])

In [219]:
Flights["Scheduled_Arrival"]=pd.to_datetime(Flights["Scheduled_Arrival"])

In [135]:
Flights["Actual_Arrival"]=pd.to_datetime(Flights["Actual_Arrival"])

In [143]:
Flights["Gate_Number"].mode()

0    G11
Name: Gate_Number, dtype: str

In [ ]:
Flights["Actual_Departure"].mode()

In [221]:
Flights["Cancellation_Reason"].mode()

0    Air Traffic Control
Name: Cancellation_Reason, dtype: str

In [222]:
Flights["Delay_Minutes"]=Flights["Delay_Minutes"].fillna(Flights["Delay_Minutes"].median())

In [223]:
Flights["Delay_Minutes"]=Flights["Delay_Minutes"].astype(int)

In [224]:
Flights["Gate_Number"]=Flights["Gate_Number"].fillna(Flights["Gate_Number"].mode()[0])

In [225]:
Flights["Cancellation_Reason"]=Flights["Cancellation_Reason"].fillna(Flights["Cancellation_Reason"].mode()[0])

In [232]:
Flights["Actual_Departure"]=Flights["Actual_Departure"].fillna(Flights["Actual_Departure"].mode()[0])

In [226]:
Flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Flight_ID                50000 non-null  str
 1   Operation_ID             50000 non-null  str
 2   Flight_Number            50000 non-null  str
 3   Origin_Airport           50000 non-null  str
 4   Destination_Airport      50000 non-null  str
 5   Departure_Date           50000 non-null  datetime64[us]
 6   Scheduled_Departure      50000 non-null  datetime64[us]
 7   Actual_Departure         48980 non-null  str
 8   Scheduled_Arrival        50000 non-null  datetime64[us]
 9   Actual_Arrival           50000 non-null  str
 10  Flight_Duration_Minutes  50000 non-null  int64
 11  Distance_KM              50000 non-null  int64
 12  Flight_Status            50000 non-null  str
 13  Gate_Number              50000 non-null  str
 14  Runway_Number            50000 non-null  str
 15  Delay_Minutes            50000 non-null  int64
 16  Cancellation_Reason      50000 non-null  str
dtypes: datetime64[us](3), int64(3), str(11)
memory usage: 11.0 MB

In [152]:
Flights["Flight_Status"].value_counts()

Flight_Status
On Time      35024
Delayed       9955
Cancelled     5021
Name: count, dtype: int64

In [153]:
Flights["Cancellation_Reason"].value_counts()

Cancellation_Reason
Air Traffic Control    46525
Technical Issue         1195
Weather                 1154
Crew Shortage           1126
Name: count, dtype: int64

In [227]:
Airline_Operations.to_csv(r"D:\Final Project\Final Project\Airline_Operations.csv",index=False)

In [228]:
Bookings.to_csv(r"D:\Final Project\Final Project\Bookings.csv",index=False)

In [229]:
Customers.to_csv(r"D:\Final Project\Final Project\Customers.csv",index=False)

In [233]:
Flights.to_csv(r"D:\Final Project\Final Project\Flights.csv",index=False)